{{- if .Values.udp

enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefik.fullname" . }}-udp
  labels:
    app.kubernetes.io/name: {{ template "traefik.name" . }}
    helm.sh/chart: {{ template "traefik.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
  {{- with .Values.udpService.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- $type := default "LoadBalancer" .Values.udpService.type }}
  type: {{ $type }}
  {{- with .Values.udpService.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "traefik.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  {{- range $name, $config := .Values.udpPorts }}
  {{- if $config.expose }}
  - port: {{ default $config.port $config.exposedPort }}
    name: {{ $name }}
    targetPort: {{ $name | quote }}
    protocol: UDP
    {{- if $config.nodePort }}
    nodePort: {{ $config.nodePort }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- if eq $type "LoadBalancer" }}
  {{- with .Values.udpService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 2 }}
  {{- end -}}
  {{- end -}}
  {{- with .Values.udpService.externalIPs }}
  externalIPs:
  {{- toYaml . | nindent 2 }}
  {{- end -}}
{{- end -}}
